"""drop fields lead

Revision ID: 78fb4cf0b184
Revises: 48f655526434
Create Date: 2025-10-21 05:31:24.556094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78fb4cf0b184'
down_revision: Union[str, Sequence[str], None] = '48f655526434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'model')
    op.drop_column('leads', 'step')
    op.drop_column('leads', 'needs')
    op.drop_column('leads', 'offer')
    op.drop_column('leads', 'motive')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('motive', sa.TEXT(), nullable=True))
    op.add_column('leads', sa.Column('offer', sa.TEXT(), nullable=True))
    op.add_column('leads', sa.Column('needs', sa.TEXT(), nullable=True))
    op.add_column('leads', sa.Column('step', sa.INTEGER(), nullable=True))
    op.add_column('leads', sa.Column('model', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
